package dux;
public class Resultados extends javax.swing.JFrame {

    /**
     * Creates new form Resultados
     */
    public Resultados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        jScrollPane6 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane24 = new javax.swing.JScrollPane();
        jTextPane21 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        nombre1 = new javax.swing.JTextField();
        nombre2 = new javax.swing.JTextField();
        set21 = new javax.swing.JTextField();
        set22 = new javax.swing.JTextField();
        set23 = new javax.swing.JTextField();
        set24 = new javax.swing.JTextField();
        set25 = new javax.swing.JTextField();
        set11 = new javax.swing.JTextField();
        set12 = new javax.swing.JTextField();
        set13 = new javax.swing.JTextField();
        set14 = new javax.swing.JTextField();
        set15 = new javax.swing.JTextField();
        taebreak11 = new javax.swing.JTextField();
        taebreak12 = new javax.swing.JTextField();
        taebreak13 = new javax.swing.JTextField();
        taebreak14 = new javax.swing.JTextField();
        taebreak15 = new javax.swing.JTextField();
        taebreak21 = new javax.swing.JTextField();
        taebreak22 = new javax.swing.JTextField();
        taebreak23 = new javax.swing.JTextField();
        taebreak24 = new javax.swing.JTextField();
        taebreak25 = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane6.setViewportView(jTable1);

        jScrollPane24.setViewportView(jTextPane21);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        set11.setEditable(false);
        set12.setEditable(false);
        set13.setEditable(false); 
        set14.setEditable(false); 
        set15.setEditable(false);
        set21.setEditable(false); 
        set22.setEditable(false); 
        set23.setEditable(false); 
        set24.setEditable(false); 
        set25.setEditable(false); 
        taebreak11.setEditable(false); 
        taebreak12.setEditable(false);
        taebreak13.setEditable(false);
        taebreak14.setEditable(false);
        taebreak15.setEditable(false);
        taebreak21.setEditable(false);
        taebreak22.setEditable(false);
        taebreak23.setEditable(false);
        taebreak24.setEditable(false);
        taebreak25.setEditable(false);
        nombre1.setEditable(false);
        nombre2.setEditable(false);
        

        taebreak11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taebreak11ActionPerformed(evt);
            }
        });

        taebreak12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                taebreak12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nombre2, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(nombre1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taebreak11, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taebreak21, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(set21, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(set11, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(taebreak22, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(taebreak12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(set22, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set12, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(taebreak23, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(set23, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(taebreak13, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(set13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(taebreak14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(set14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(taebreak24, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(set24, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(taebreak15, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(taebreak25, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(set15, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(set25, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGap(80, 80, 80))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taebreak12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taebreak11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taebreak13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taebreak14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taebreak15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombre2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(set25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(taebreak21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(87, 87, 87))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(taebreak22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taebreak23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taebreak24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(taebreak25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void taebreak11ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void taebreak12ActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          



    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane21;
    private javax.swing.JTextField nombre1;
    private javax.swing.JTextField nombre2;
    private javax.swing.JTextField set11;
    private javax.swing.JTextField set12;
    private javax.swing.JTextField set13;
    private javax.swing.JTextField set14;
    private javax.swing.JTextField set15;
    private javax.swing.JTextField set21;
    private javax.swing.JTextField set22;
    private javax.swing.JTextField set23;
    private javax.swing.JTextField set24;
    private javax.swing.JTextField set25;
    private javax.swing.JTextField taebreak11;
    private javax.swing.JTextField taebreak12;
    private javax.swing.JTextField taebreak13;
    private javax.swing.JTextField taebreak14;
    private javax.swing.JTextField taebreak15;
    private javax.swing.JTextField taebreak21;
    private javax.swing.JTextField taebreak22;
    private javax.swing.JTextField taebreak23;
    private javax.swing.JTextField taebreak24;
    private javax.swing.JTextField taebreak25;


  public void cargarNombres(Jugadores jugador1, Jugadores jugador2) {
    	nombre1.setText(jugador1.getNombre());
    	nombre2.setText(jugador2.getNombre());
    }
  public void cargarResultadosTaebreak(Jugadores jugador1, Jugadores jugador2, int setJugados) {
	  if(setJugados==3) {
			if(jugador1.getPuntosTeabreak().get(0)!=0) {
				taebreak11.setText(jugador1.getPuntosTeabreak().get(0).toString());
			}
			else {
				taebreak11.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(1)!=0) {
				taebreak12.setText(jugador1.getPuntosTeabreak().get(1).toString());
			}
			else {
				taebreak12.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(2)!=0) {
				taebreak13.setText(jugador1.getPuntosTeabreak().get(2).toString());
			}
			else {
				taebreak13.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(0)!=0) {
				taebreak21.setText(jugador2.getPuntosTeabreak().get(0).toString());
			}
			else {
				taebreak21.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(1)!=0) {
				taebreak22.setText(jugador2.getPuntosTeabreak().get(1).toString());
			}
			else {
				taebreak22.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(2)!=0) {
				taebreak23.setText(jugador2.getPuntosTeabreak().get(2).toString());
			}
			else {
				taebreak23.setText("N/A");
			}
			
		}
		if(setJugados==4) {
			if(jugador1.getPuntosTeabreak().get(0)!=0) {
				taebreak11.setText(jugador1.getPuntosTeabreak().get(0).toString());
			}
			else {
				taebreak11.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(1)!=0) {
				taebreak12.setText(jugador1.getPuntosTeabreak().get(1).toString());
			}
			else {
				taebreak12.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(2)!=0) {
				taebreak13.setText(jugador1.getPuntosTeabreak().get(2).toString());
			}
			else {
				taebreak13.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(3)!=0) {
				taebreak14.setText(jugador1.getPuntosTeabreak().get(3).toString());
			}
			else {
				taebreak14.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(0)!=0) {
				taebreak21.setText(jugador2.getPuntosTeabreak().get(0).toString());
			}
			else {
				taebreak21.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(1)!=0) {
				taebreak22.setText(jugador2.getPuntosTeabreak().get(1).toString());
			}
			else {
				taebreak22.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(2)!=0) {
				taebreak23.setText(jugador2.getPuntosTeabreak().get(2).toString());
			}
			else {
				taebreak23.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(3)!=0) {
				taebreak24.setText(jugador2.getPuntosTeabreak().get(3).toString());
			}
			else {
				taebreak24.setText("N/A");
			}
		}
		if(setJugados==5) {
			if(jugador1.getPuntosTeabreak().get(0)!=0) {
				taebreak11.setText(jugador1.getPuntosTeabreak().get(0).toString());
			}
			else {
				taebreak11.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(1)!=0) {
				taebreak12.setText(jugador1.getPuntosTeabreak().get(1).toString());
			}
			else {
				taebreak12.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(2)!=0) {
				taebreak13.setText(jugador1.getPuntosTeabreak().get(2).toString());
			}
			else {
				taebreak13.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(3)!=0) {
				taebreak14.setText(jugador1.getPuntosTeabreak().get(3).toString());
			}
			else {
				taebreak14.setText("N/A");
			}
			if(jugador1.getPuntosTeabreak().get(4)!=0) {
				taebreak15.setText(jugador1.getPuntosTeabreak().get(4).toString());
			}
			else {
				taebreak15.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(0)!=0) {
				taebreak21.setText(jugador2.getPuntosTeabreak().get(0).toString());
			}
			else {
				taebreak21.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(1)!=0) {
				taebreak22.setText(jugador2.getPuntosTeabreak().get(1).toString());
			}
			else {
				taebreak22.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(2)!=0) {
				taebreak23.setText(jugador2.getPuntosTeabreak().get(2).toString());
			}
			else {
				taebreak23.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(3)!=0) {
				taebreak24.setText(jugador2.getPuntosTeabreak().get(3).toString());
			}
			else {
				taebreak24.setText("N/A");
			}
			if(jugador2.getPuntosTeabreak().get(4)!=0) {
				taebreak25.setText(jugador2.getPuntosTeabreak().get(4).toString());
			}
			else {
				taebreak25.setText("N/A");
			}
		}
  }
public void cargarResultadosSets(Jugadores jugador1, Jugadores jugador2, int setJugados) {
	if(setJugados==3) {
		if(jugador1.getPuntosSets().get(0)!=null) {
			set11.setText(jugador1.getPuntosSets().get(0).toString());
		}
		else {
			set11.setText("0");
		}
		if(jugador1.getPuntosSets().get(1)!=null) {
			set12.setText(jugador1.getPuntosSets().get(1).toString());
		}
		else {
			set12.setText("0");
		}
		if(jugador1.getPuntosSets().get(2)!=null) {
			set13.setText(jugador1.getPuntosSets().get(2).toString());
		}
		else {
			set13.setText("0");
		}
		
		if(jugador2.getPuntosSets().get(0)!=null) {
			set21.setText(jugador2.getPuntosSets().get(0).toString());
		}
		else {
			set21.setText("0");
		}
		if(jugador2.getPuntosSets().get(1)!=null) {
			set22.setText(jugador2.getPuntosSets().get(1).toString());
		}
		else {
			set22.setText("0");
		}
		if(jugador2.getPuntosSets().get(2)!=null) {
			set23.setText(jugador2.getPuntosSets().get(2).toString());
		}
		else {
			set23.setText("0");
		}
		
	}
	if(setJugados==4) {
		if(jugador1.getPuntosSets().get(0)!=null) {
			set11.setText(jugador1.getPuntosSets().get(0).toString());
		}
		else {
			set11.setText("0");
		}
		if(jugador1.getPuntosSets().get(1)!=null) {
			set12.setText(jugador1.getPuntosSets().get(1).toString());
		}
		else {
			set12.setText("0");
		}
		if(jugador1.getPuntosSets().get(2)!=null) {
			set13.setText(jugador1.getPuntosSets().get(2).toString());
		}
		else {
			set13.setText("0");
		}
		if(jugador1.getPuntosSets().get(3)!=null) {
			set14.setText(jugador1.getPuntosSets().get(3).toString());
		}
		else {
			set14.setText("0");
		}
		
		if(jugador2.getPuntosSets().get(0)!=null) {
			set21.setText(jugador2.getPuntosSets().get(0).toString());
		}
		else {
			set21.setText("0");
		}
		if(jugador2.getPuntosSets().get(1)!=null) {
			set22.setText(jugador2.getPuntosSets().get(1).toString());
		}
		else {
			set22.setText("0");
		}
		if(jugador2.getPuntosSets().get(2)!=null) {
			set23.setText(jugador2.getPuntosSets().get(2).toString());
		}
		else {
			set23.setText("0");
		}
		if(jugador2.getPuntosSets().get(3)!=null) {
			set24.setText(jugador2.getPuntosSets().get(3).toString());
		}
		else {
			set24.setText("0");
		}
	}
	if(setJugados==5) {
		if(jugador1.getPuntosSets().get(0)!=null) {
			set11.setText(jugador1.getPuntosSets().get(0).toString());
		}
		else {
			set11.setText("0");
		}
		if(jugador1.getPuntosSets().get(1)!=null) {
			set12.setText(jugador1.getPuntosSets().get(1).toString());
		}
		else {
			set12.setText("0");
		}
		if(jugador1.getPuntosSets().get(2)!=null) {
			set13.setText(jugador1.getPuntosSets().get(2).toString());
		}
		else {
			set13.setText("0");
		}
		if(jugador1.getPuntosSets().get(3)!=null) {
			set14.setText(jugador1.getPuntosSets().get(3).toString());
		}
		else {
			set14.setText("0");
		}
		if(jugador1.getPuntosSets().get(4)!=null) {
			set15.setText(jugador1.getPuntosSets().get(4).toString());
		}
		else {
			set24.setText("0");
		}
		
		if(jugador2.getPuntosSets().get(0)!=null) {
			set21.setText(jugador2.getPuntosSets().get(0).toString());
		}
		else {
			set21.setText("0");
		}
		if(jugador2.getPuntosSets().get(1)!=null) {
			set22.setText(jugador2.getPuntosSets().get(1).toString());
		}
		else {
			set22.setText("0");
		}
		if(jugador2.getPuntosSets().get(2)!=null) {
			set23.setText(jugador2.getPuntosSets().get(2).toString());
		}
		else {
			set23.setText("0");
		}
		if(jugador2.getPuntosSets().get(3)!=null) {
			set24.setText(jugador2.getPuntosSets().get(3).toString());
		}
		else {
			set24.setText("0");
		}
		if(jugador2.getPuntosSets().get(4)!=null) {
			set25.setText(jugador2.getPuntosSets().get(4).toString());
		}
		else {
			set25.setText("0");
		}
	}
	
}


}
